### PR TITLE
Order has been fixed

### PR DESCRIPTION
**Pull request by ghost**
The order method was unfinished.

### CODE REVIEW

**Comment by IgorJakovljevic** [comment]
Great, thanks  :D Will update PIP tomorrow

**Comment by ghost** [comment]
You are welcome :)

**Comment by IgorJakovljevic** [comment]
@hmikihth If you want to test it out via PIP you can, because I just uploaded a new version :D Thanks again for the fix

**Comment by ghost** [comment]
@IgorJakovljevic Ok, I will test it tonight.

**Comment by ghost** [comment]
@IgorJakovljevic I have tried the PIP package, that works fine. Thanks for the update  :)

**Pull request merged**
